import SwiftUI

struct ReportsScreen: View {
    let open: (AtlasRoute) -> Void
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        AtlasPage {
            ScrollView(showsIndicators: false) {
                VStack(alignment: .leading, spacing: 26) {
                    AtlasEditorialHeader(
                        eyebrow: "REPORTS",
                        title: "Documentos que explican, no que decoran.",
                        subtitle: "Inspecciones, historial de activos, condición, cambios y mantenimiento.",
                        backAction: { dismiss() }
                    )

                    reportGroup("01", "INSPECTION REPORTS", [
                        ("Inspección M-028", "20 sep · 7 evidencias"),
                        ("Entrega Apartamento Norte", "19 sep · 18 evidencias")
                    ])
                    reportGroup("02", "CHANGE REPORTS", [
                        ("Estudio 04 / Estado 017 → 018", "18–20 sep · 4 cambios")
                    ])
                    reportGroup("03", "MAINTENANCE REPORTS", [
                        ("M-028 / Historial preventivo", "Jun–sep 2026")
                    ])
                }
                .padding(20)
            }
        }
    }

    private func reportGroup(_ index: String, _ title: String, _ rows: [(String, String)]) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            AtlasSectionLabel(index: index, title: title)
            ForEach(Array(rows.enumerated()), id: \.offset) { idx, row in
                Button { open(.reportDetail) } label: {
                    HStack(alignment: .top, spacing: 12) {
                        Image(systemName: "doc.text")
                            .foregroundStyle(AtlasColor.blue)
                            .frame(width: 28)
                        VStack(alignment: .leading, spacing: 4) {
                            Text(row.0).font(AtlasType.heading(.headline, weight: .semibold)).foregroundStyle(AtlasColor.ink)
                            Text(row.1).font(AtlasType.body(.caption)).foregroundStyle(AtlasColor.inkMuted)
                        }
                        Spacer()
                        Image(systemName: "chevron.right")
                            .font(.system(size: 12, weight: .semibold))
                            .foregroundStyle(AtlasColor.inkMuted)
                    }
                    .padding(.vertical, 14)
                }
                .buttonStyle(AtlasPressButtonStyle())
                if idx < rows.count - 1 { AtlasDivider() }
            }
        }
    }
}

struct ReportDetailScreen: View {
    @Environment(\.dismiss) private var dismiss
    @State private var showShare = false

    var body: some View {
        AtlasPage {
            ScrollView(showsIndicators: false) {
                VStack(alignment: .leading, spacing: 28) {
                    AtlasEditorialHeader(
                        eyebrow: "REPORT / CONDITION",
                        title: "Unidad M-028 · Estado y condición.",
                        subtitle: "Periodo · 14–20 septiembre 2026",
                        backAction: { dismiss() },
                        trailingSymbol: "square.and.arrow.up",
                        trailingAction: { showShare = true }
                    )

                    Text("RESUMEN")
                        .font(AtlasType.label(.caption2, weight: .semibold))
                        .tracking(0.8)
                        .foregroundStyle(AtlasColor.blue)
                    Text("La condición general se mantiene estable. Se recomienda revisar el sistema de montaje por una variación visual presente en dos inspecciones consecutivas.")
                        .font(AtlasType.heading(.title2, weight: .semibold))
                        .foregroundStyle(AtlasColor.ink)
                        .lineSpacing(4)

                    reportSection("01", "FINDINGS", "1 hallazgo en seguimiento · 0 críticos")
                    reportSection("02", "CHANGES", "2 variaciones visuales · sin cambio de condición general")
                    reportSection("03", "EVIDENCE", "7 fotografías · 2 estados · OCR disponible")
                    reportSection("04", "RECOMMENDATIONS", "Inspeccionar fijaciones antes de la próxima operación prolongada.")

                    HStack {
                        Text("GENERATED BY ATLAS")
                            .font(AtlasType.mono(.caption2, weight: .semibold))
                            .foregroundStyle(AtlasColor.inkMuted)
                        Spacer()
                        Text("20 SEP 2026 · 15:48")
                            .font(AtlasType.mono(.caption2))
                            .foregroundStyle(AtlasColor.inkMuted)
                    }
                    .padding(.top, 12)

                    AtlasPrimaryButton(title: "Exportar / Compartir", symbol: "square.and.arrow.up") { showShare = true }
                }
                .padding(20)
            }
        }
        .sheet(isPresented: $showShare) {
            ReportShareSheet()
                .presentationDetents([.medium])
        }
    }

    private func reportSection(_ index: String, _ title: String, _ value: String) -> some View {
        VStack(alignment: .leading, spacing: 10) {
            AtlasSectionLabel(index: index, title: title)
            Text(value)
                .font(AtlasType.body(.body))
                .foregroundStyle(AtlasColor.inkSecondary)
                .lineSpacing(4)
        }
    }
}

private struct ReportShareSheet: View {
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        VStack(alignment: .leading, spacing: 20) {
            Text("Exportar reporte")
                .font(AtlasType.heading(.title2))
                .foregroundStyle(AtlasColor.ink)
            Text("La generación de PDF y el destino de exportación se conectarán al backend/document engine. La UI no afirma que el archivo ya exista.")
                .font(AtlasType.body(.body))
                .foregroundStyle(AtlasColor.inkSecondary)
                .lineSpacing(4)
            PrimaryActionRow(title: "PDF", subtitle: "Preparar documento", symbol: "doc.richtext") { dismiss() }
            AtlasDivider()
            PrimaryActionRow(title: "Compartir enlace", subtitle: "Disponible cuando exista sincronización remota", symbol: "link") { dismiss() }
        }
        .padding(24)
        .background(AtlasColor.background)
    }
}
